version: 2.1
jobs:
  test:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - run:
          name: Install deps
          command: |
            set -e
            apt-get update
            apt-get --quiet --yes install gettext-base wget
            wget https://github.com/mikefarah/yq/releases/download/v4.14.1/yq_linux_arm64 -O /usr/bin/yq
            shasum /usr/bin/yq | grep -q b01750ecc56b739b61d641a2a4797aa96ba8c8f4
            chmod +x /usr/bin/yq

      # build and push Docker image
      - run:
          name: Test
          command: test/test.sh
  build:
    docker:
      - image: docker:stable-git
    steps:
      - checkout
      - run:
          name: Prepare build environment
          command: |
            apk update
            apk --upgrade add build-base rsync curl jq

      - setup_remote_docker:
          version: 20.10.6

      # build and push Docker image
      - run:
          name: Build image and push to Docker Hub
          command: |
            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
            make

workflows:
  test:
    jobs:
      - test:
          filters:
            branches:
              ignore:
                - main
  commit:
    jobs:
      - hold:
          type: approval
          filters:
            branches:
              only:
                - main
      - build:
          requires:
            - hold
  build:
    triggers:
      - schedule:
          # 3am every Saturday
          cron: "0 3 * * 6"
          filters:
            branches:
              only: main
    jobs:
      - build
