version: 2.1
jobs:
  test:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - run:
          name: Install deps
          command: |
            set -e
            curl -fsSL https://deb.nodesource.com/setup_18.x | sudo bash -
            sudo apt-get --quiet --yes install nodejs
            npm --prefix dist ci

      - run:
          name: Test
          command: test/test.sh
  build:
    docker:
      - image: docker:stable-git
    steps:
      - checkout
      - run:
          name: Prepare build environment
          command: |
            apk update
            apk --upgrade add build-base rsync curl jq

      - setup_remote_docker:
          version: 20.10.14

      # build and push Docker image
      - run:
          name: Build image and push to Docker Hub
          command: |
            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
            make

workflows:
  test:
    jobs:
      - test:
          filters:
            branches:
              ignore:
                - main
  commit:
    jobs:
      - hold:
          type: approval
          filters:
            branches:
              only:
                - main
      - build:
          requires:
            - hold
  build:
    triggers:
      - schedule:
          # 3am every Saturday
          cron: "0 3 * * 6"
          filters:
            branches:
              only: main
    jobs:
      - build
